FROM node:17-alpine

WORKDIR /app

COPY package*.json ./

RUN yarn install

# Copy all the application code to the container
COPY . .

# Expose port 3016 for the application
EXPOSE 3000

# Define the command to start the application
CMD ["yarn", "start"]
