import { createTheme } from '@fluentui/react';

export const darkTheme = createTheme({
  palette: {
    themePrimary: '#0dbd0d',
    themeLighterAlt: '#f3fcf3',
    themeLighter: '#d0f4d0',
    themeLight: '#aaebaa',
    themeTertiary: '#5fd75f',
    themeSecondary: '#24c524',
    themeDarkAlt: '#0caa0c',
    themeDark: '#0a8f0a',
    themeDarker: '#076a07',
    neutralLighterAlt: '#323232',
    neutralLighter: '#313131',
    neutralLight: '#2f2f2f',
    neutralQuaternaryAlt: '#2c2c2c',
    neutralQuaternary: '#2a2a2a',
    neutralTertiaryAlt: '#282828',
    neutralTertiary: '#c8c8c8',
    neutralSecondary: '#d0d0d0',
    neutralPrimaryAlt: '#dadada',
    neutralPrimary: '#ffffff',
    neutralDark: '#f4f4f4',
    black: '#f8f8f8',
    white: '#333333',
  }});

  export const lightTheme = createTheme({
    palette: {
      themePrimary: '#28bd32',
      themeLighterAlt: '#f4fcf5',
      themeLighter: '#d6f4d8',
      themeLight: '#b3ebb7',
      themeTertiary: '#71d778',
      themeSecondary: '#3cc545',
      themeDarkAlt: '#24aa2d',
      themeDark: '#1e8f26',
      themeDarker: '#166a1c',
      neutralLighterAlt: '#d5d1d1',
      neutralLighter: '#d2cece',
      neutralLight: '#c9c5c5',
      neutralQuaternaryAlt: '#bcb8b8',
      neutralQuaternary: '#b3afaf',
      neutralTertiaryAlt: '#aca8a8',
      neutralTertiary: '#a19f9d',
      neutralSecondary: '#605e5c',
      neutralPrimaryAlt: '#3b3a39',
      neutralPrimary: '#323130',
      neutralDark: '#201f1e',
      black: '#000000',
      white: '#dbd7d7',
    }});
