name: Build and Push Docker Images

on:
    pull_request:
        branches:
            - master
        types: [closed]

jobs:
    build-and-push:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              with:
                  platforms: all

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Install dependencies and build
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Build
              run: |
                  yarn install
                  yarn build

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: mikicv/pihole-switcher:latest
                  platforms: linux/amd64,linux/386
