name: Build and Push Docker Images

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    release:
        types: [published]

jobs:
    build-and-push:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              with:
                  platforms: all

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: mikicv/pihole-switcher:latest
                  platforms: linux/amd64,linux/386

    create-release:
        needs: build-and-push
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Create GitHub Release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: Release ${{ github.ref_name }}
                  draft: false
                  prerelease: false
                  files: mikicv/pihole-switcher:latest
