name: Build and Push Docker Images

on:
    pull_request:
        branches:
            - master
        types: [closed]
    workflow_dispatch:

jobs:
    build-and-push:
        if: github.event.pull_request.merged == true || github.actor == 'mikicvi'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
              with:
                  platforms: linux/amd64,linux/arm64,linux/arm/v7

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Install dependencies and build
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'yarn'

            - name: Build
              run: |
                  yarn install --frozen-lockfile
                  yarn build

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: mikicv/pihole-switcher
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=sha,prefix={{branch}}-
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  platforms: linux/amd64,linux/arm64,linux/arm/v7
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
